#!/usr/bin/env python3
"""Host-side Nr 3 tenant provisioner.

Runs as root on the VPS, outside the FastAPI container. It consumes JSON
jobs written by the Nr 3 app into ./data/provisioning/jobs and performs
the privileged host operations: writing /root/clients, Docker Compose,
nginx config, nginx reload, and health check.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SLUG_RE = re.compile(r"^[a-z][a-z0-9_-]{1,49}$")
RESERVED_SLUGS = {"unboks"}


def env_path(name: str, default: str) -> Path:
    return Path(os.getenv(name, default).strip() or default)


QUEUE_DIR = env_path(
    "NR3_PROVISION_QUEUE_DIR",
    "/root/unboks-internal-control-panel/data/provisioning/jobs",
)
RESULT_DIR = env_path(
    "NR3_PROVISION_RESULT_DIR",
    "/root/unboks-internal-control-panel/data/provisioning/results",
)
FAILED_DIR = env_path(
    "NR3_PROVISION_FAILED_DIR",
    "/root/unboks-internal-control-panel/data/provisioning/failed",
)
CLIENTS_ROOT = env_path("NR3_PROVISION_CLIENTS_ROOT", "/root/clients")
NGINX_SITE = env_path("NR3_PROVISION_NGINX_SITE", "/etc/nginx/sites-enabled/api-unboks")
BRIDGE_TOKEN_FILE = env_path(
    "NR3_PROVISION_BRIDGE_TOKEN_FILE",
    "/root/clients/_shared/nr3_internal_api_token",
)
NGINX_BACKUP_DIR = env_path(
    "NR3_PROVISION_NGINX_BACKUP_DIR",
    "/root/nginx-sites-enabled-backups",
)
POLL_SECONDS = float(os.getenv("NR3_PROVISION_POLL_SECONDS", "2"))


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def run(cmd: list[str], *, cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        check=check,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )


def write_result(job_id: str, payload: dict[str, Any]) -> None:
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    payload.setdefault("finished_at", utc_now())
    tmp = RESULT_DIR / f".{job_id}.tmp"
    final = RESULT_DIR / f"{job_id}.json"
    tmp.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    os.replace(tmp, final)


def read_bridge_token() -> str:
    token = BRIDGE_TOKEN_FILE.read_text(encoding="utf-8").strip()
    if not token:
        raise RuntimeError(f"Bridge token file is empty: {BRIDGE_TOKEN_FILE}")
    return token


def platform_env_text(slug: str, password: str, created_at: str, token: str) -> str:
    return (
        f"# platform.env for tenant {slug}\n"
        f"# Generated by Nr3 at {created_at}\n"
        f"DASHBOARD_PASSWORD={password}\n"
        f"TENANT_ID={slug}\n"
        f"TENANT_SLUG={slug}\n"
        f"NR3_INTERNAL_OVERRIDES_URL=http://wtyj-admin:8010\n"
        f"NR3_INTERNAL_API_TOKEN={token}\n"
        f"ICP_OVERRIDES_TTL_SECONDS=5\n"
    )


def insert_nginx_block(slug: str, block: str) -> None:
    text = NGINX_SITE.read_text(encoding="utf-8")
    # Never place backups inside sites-enabled; nginx reads every file
    # there and backup copies create duplicate server_name warnings.
    NGINX_BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    backup = NGINX_BACKUP_DIR / (
        f"{NGINX_SITE.name}.bak-nr3-{slug}-"
        f"{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
    )
    shutil.copy2(NGINX_SITE, backup)

    start = f"# BEGIN UNBOKS TENANT {slug}"
    end = f"# END UNBOKS TENANT {slug}"
    while start in text and end in text:
        before, rest = text.split(start, 1)
        _, after = rest.split(end, 1)
        text = before.rstrip() + "\n" + after.lstrip("\n")

    marker = "    server_name api.unboks.org;\n"
    if marker not in text:
        marker = "server_name api.unboks.org;\n"
    if marker not in text:
        raise RuntimeError("Could not find server_name api.unboks.org in nginx site file")
    text = text.replace(marker, marker + "\n" + block + "\n", 1)
    NGINX_SITE.write_text(text, encoding="utf-8")

    try:
        run(["nginx", "-t"])
    except subprocess.CalledProcessError:
        shutil.copy2(backup, NGINX_SITE)
        raise


def wait_for_health(host_port: int, timeout: int = 45) -> str:
    url = f"http://127.0.0.1:{host_port}/health"
    deadline = time.monotonic() + timeout
    last_error = ""
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=4) as response:
                body = response.read(300).decode("utf-8", errors="replace")
                if 200 <= response.status < 500:
                    return f"{url} -> HTTP {response.status} {body}".strip()
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            last_error = str(exc)
        time.sleep(2)
    raise RuntimeError(f"Tenant health check timed out for {url}: {last_error}")


def validate_slug(raw: object) -> str:
    slug = str(raw or "")
    if not SLUG_RE.match(slug):
        raise RuntimeError(f"Invalid slug in provisioning job: {slug!r}")
    return slug


def update_client_status(tenant_dir: Path, status: str) -> None:
    client_path = tenant_dir / "config" / "client.json"
    data = json.loads(client_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise RuntimeError(f"client.json is not an object: {client_path}")
    business = data.get("business")
    if isinstance(business, dict) and business:
        business["status"] = status
    data["status"] = status
    client_path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def process_tenant_action(job_id: str, job: dict[str, Any]) -> None:
    action = str(job.get("action") or "")
    slug = validate_slug(job.get("slug"))
    if slug in RESERVED_SLUGS:
        raise RuntimeError(f"Tenant {slug!r} is reserved and cannot be changed by host action.")
    if action != "suspend_tenant":
        raise RuntimeError(f"Unsupported tenant action: {action!r}")

    tenant_dir = CLIENTS_ROOT / slug
    if not tenant_dir.is_dir():
        raise RuntimeError(f"Tenant directory not found: {tenant_dir}")
    details: list[str] = []
    update_client_status(tenant_dir, "suspended")
    details.append("client.json status set to suspended")
    run(["docker", "compose", "stop"], cwd=tenant_dir)
    details.append(f"docker compose stop completed for {slug}")
    dashboard_url = str(job.get("dashboard_url") or f"https://dashboard.unboks.org/{slug}")
    write_result(job_id, {
        "status": "succeeded",
        "message": f"Tenant {slug} was suspended on the VPS.",
        "details": details,
        "dashboard_url": dashboard_url,
    })


def process_job(job_path: Path) -> None:
    processing_path = job_path.with_suffix(".processing")
    try:
        os.replace(job_path, processing_path)
    except FileNotFoundError:
        return

    job_id = processing_path.stem
    details: list[str] = []
    try:
        job = json.loads(processing_path.read_text(encoding="utf-8"))
        job_id = str(job.get("job_id") or job_id)
        if job.get("job_type") == "tenant_action":
            process_tenant_action(job_id, job)
            processing_path.unlink(missing_ok=True)
            return
        slug = validate_slug(job.get("slug"))
        host_port = int(job["host_port"])
        if host_port < 1 or host_port > 65535:
            raise RuntimeError(f"Invalid host port in provisioning job: {host_port}")
        client_data = job.get("client_data")
        if not isinstance(client_data, dict):
            raise RuntimeError("client_data must be a JSON object")
        if client_data.get("slug") != slug:
            raise RuntimeError("client_data.slug does not match job slug")
        password = str(client_data.get("password") or "")
        if len(password) < 8:
            raise RuntimeError("client_data.password is missing or too short")
        docker_compose_text = str(job.get("docker_compose_text") or "")
        if f"container_name: wtyj-{slug}" not in docker_compose_text:
            raise RuntimeError("docker compose text does not target this tenant slug")
        nginx_block = str(job.get("managed_nginx_block_text") or "")
        if f"/api/{slug}/" not in nginx_block:
            raise RuntimeError("nginx block does not target this tenant slug")

        tenant_dir = CLIENTS_ROOT / slug
        if tenant_dir.exists():
            raise RuntimeError(f"Tenant directory already exists: {tenant_dir}")
        token = read_bridge_token()

        (tenant_dir / "config").mkdir(parents=True)
        (tenant_dir / "data").mkdir()
        (tenant_dir / "logs").mkdir()
        (tenant_dir / "config" / "client.json").write_text(
            json.dumps(client_data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        (tenant_dir / "config" / "platform.env").write_text(
            platform_env_text(slug, password, str(client_data.get("created_at") or utc_now()), token),
            encoding="utf-8",
        )
        (tenant_dir / "docker-compose.yml").write_text(docker_compose_text.rstrip() + "\n", encoding="utf-8")
        details.append(f"wrote tenant files under {tenant_dir}")

        inspect = run(["docker", "network", "inspect", "unboks-control"], check=False)
        if inspect.returncode != 0:
            run(["docker", "network", "create", "unboks-control"])
            details.append("created docker network unboks-control")

        run(["docker", "compose", "up", "-d"], cwd=tenant_dir)
        details.append(f"started docker compose for {slug}")

        insert_nginx_block(slug, nginx_block)
        run(["systemctl", "reload", "nginx"])
        details.append("nginx config tested and reloaded")

        health = wait_for_health(host_port)
        details.append(health)

        dashboard_url = str(job.get("dashboard_url") or f"https://dashboard.unboks.org/{slug}")
        write_result(job_id, {
            "status": "succeeded",
            "message": f"Tenant {slug} was provisioned on the VPS.",
            "details": details,
            "dashboard_url": dashboard_url,
            "health_url": f"http://127.0.0.1:{host_port}/health",
        })
        processing_path.unlink(missing_ok=True)
    except Exception as exc:
        FAILED_DIR.mkdir(parents=True, exist_ok=True)
        failed_copy = FAILED_DIR / processing_path.name
        try:
            os.replace(processing_path, failed_copy)
        except OSError:
            pass
        write_result(job_id, {
            "status": "failed",
            "message": str(exc),
            "details": details,
        })


def run_forever() -> None:
    QUEUE_DIR.mkdir(parents=True, exist_ok=True)
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    FAILED_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Nr3 provision worker watching {QUEUE_DIR}", flush=True)
    while True:
        for job_path in sorted(QUEUE_DIR.glob("*.json")):
            process_job(job_path)
        time.sleep(POLL_SECONDS)


def run_once() -> None:
    QUEUE_DIR.mkdir(parents=True, exist_ok=True)
    for job_path in sorted(QUEUE_DIR.glob("*.json")):
        process_job(job_path)


if __name__ == "__main__":
    if os.geteuid() != 0:
        print("nr3_provision_worker.py must run as root", file=sys.stderr)
        raise SystemExit(1)
    if "--once" in sys.argv:
        run_once()
    else:
        run_forever()
