"""Persistent channel connection state for Nr3.

The WhatsApp/Zernio authorization flow needs durable state that is separate
from tenant runtime files and separate from browser-visible settings. This
module owns the SQLite schema and helpers for:

* connection requests generated by the operator
* completed tenant channel connections
* tenant metadata fields used by provider integrations

Raw callback state tokens are never stored; only SHA-256 hashes are persisted.
"""

from __future__ import annotations

import hashlib
import json
import secrets
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from app.config import get_settings


CONNECTION_REQUEST_STATUSES = {
    "pending",
    "auth_started",
    "callback_received",
    "pending_number",
    "connected",
    "failed",
    "expired",
    "cancelled",
}

TENANT_CONNECTION_STATUSES = {
    "not_connected",
    "pending",
    "connected",
    "failed",
    "disabled",
}


@dataclass(frozen=True)
class ConnectionRequest:
    id: str
    tenant_id: str
    channel: str
    provider: str
    status: str
    state_token_hash: str
    state_token_created_at: str
    state_token_expires_at: str | None
    auth_url: str | None
    zernio_profile_id: str | None
    zernio_account_id: str | None
    selected_phone_number_id: str | None
    display_phone_number: str | None
    callback_payload_json: str | None
    error_summary: str | None
    created_at: str
    updated_at: str


@dataclass(frozen=True)
class CreatedConnectionRequest:
    request: ConnectionRequest
    state_token: str


@dataclass(frozen=True)
class TenantChannelConnection:
    id: int
    tenant_id: str
    channel: str
    provider: str
    status: str
    zernio_profile_id: str | None
    zernio_account_id: str | None
    phone_number_id: str | None
    display_phone_number: str | None
    waba_id: str | None
    metadata_json: str
    last_request_id: str | None
    last_error: str | None
    connected_at: str | None
    created_at: str
    updated_at: str


def _connect() -> sqlite3.Connection:
    settings = get_settings()
    db_path = Path(settings.db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    """Create or upgrade channel-connection tables idempotently."""
    with _connect() as conn:
        _ensure_tenants_table(conn)
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS connection_requests (
                id TEXT PRIMARY KEY,
                tenant_id TEXT NOT NULL,
                channel TEXT NOT NULL DEFAULT 'whatsapp',
                provider TEXT NOT NULL DEFAULT 'zernio',
                status TEXT NOT NULL DEFAULT 'pending',
                state_token_hash TEXT NOT NULL UNIQUE,
                state_token_created_at TEXT NOT NULL,
                state_token_expires_at TEXT,
                auth_url TEXT,
                zernio_profile_id TEXT,
                zernio_account_id TEXT,
                selected_phone_number_id TEXT,
                display_phone_number TEXT,
                callback_payload_json TEXT,
                error_summary TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                CHECK (
                    status IN (
                        'pending',
                        'auth_started',
                        'callback_received',
                        'pending_number',
                        'connected',
                        'failed',
                        'expired',
                        'cancelled'
                    )
                )
            )
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_connection_requests_tenant_channel
            ON connection_requests (tenant_id, channel, provider, updated_at)
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS tenant_channel_connections (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tenant_id TEXT NOT NULL,
                channel TEXT NOT NULL,
                provider TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'not_connected',
                zernio_profile_id TEXT,
                zernio_account_id TEXT,
                phone_number_id TEXT,
                display_phone_number TEXT,
                waba_id TEXT,
                metadata_json TEXT NOT NULL DEFAULT '{}',
                last_request_id TEXT,
                last_error TEXT,
                connected_at TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                UNIQUE (tenant_id, channel, provider),
                CHECK (
                    status IN (
                        'not_connected',
                        'pending',
                        'connected',
                        'failed',
                        'disabled'
                    )
                )
            )
            """
        )
        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_tenant_channel_connections_tenant
            ON tenant_channel_connections (tenant_id, channel, provider)
            """
        )


def _ensure_tenants_table(conn: sqlite3.Connection) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS tenants (
            slug TEXT PRIMARY KEY,
            name TEXT,
            status TEXT NOT NULL DEFAULT 'active',
            zernio_profile_id TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    existing = {
        str(row["name"])
        for row in conn.execute("PRAGMA table_info(tenants)").fetchall()
    }
    migrations = {
        "zernio_profile_id": "ALTER TABLE tenants ADD COLUMN zernio_profile_id TEXT",
        "created_at": "ALTER TABLE tenants ADD COLUMN created_at TEXT",
        "updated_at": "ALTER TABLE tenants ADD COLUMN updated_at TEXT",
    }
    for column, statement in migrations.items():
        if column not in existing:
            conn.execute(statement)


def create_connection_request(
    *,
    tenant_id: str,
    auth_url: str | None = None,
    zernio_profile_id: str | None = None,
    channel: str = "whatsapp",
    provider: str = "zernio",
    expires_in_minutes: int = 60,
) -> CreatedConnectionRequest:
    init_db()
    now = utc_now()
    request_id = f"cr_{secrets.token_urlsafe(18)}"
    state_token = secrets.token_urlsafe(48)
    expires_at = (
        datetime.now(timezone.utc) + timedelta(minutes=expires_in_minutes)
    ).isoformat(timespec="seconds")
    with _connect() as conn:
        conn.execute(
            """
            INSERT INTO connection_requests (
                id,
                tenant_id,
                channel,
                provider,
                status,
                state_token_hash,
                state_token_created_at,
                state_token_expires_at,
                auth_url,
                zernio_profile_id,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                request_id,
                tenant_id,
                channel,
                provider,
                hash_state_token(state_token),
                now,
                expires_at,
                auth_url,
                zernio_profile_id,
                now,
                now,
            ),
        )
        row = conn.execute(
            "SELECT * FROM connection_requests WHERE id = ?",
            (request_id,),
        ).fetchone()
    return CreatedConnectionRequest(
        request=row_to_connection_request(row),
        state_token=state_token,
    )


def get_connection_request(request_id: str) -> ConnectionRequest | None:
    init_db()
    with _connect() as conn:
        row = conn.execute(
            "SELECT * FROM connection_requests WHERE id = ?",
            (request_id,),
        ).fetchone()
    return row_to_connection_request(row) if row is not None else None


def find_connection_request_by_state_token(
    state_token: str,
) -> ConnectionRequest | None:
    init_db()
    with _connect() as conn:
        row = conn.execute(
            """
            SELECT * FROM connection_requests
            WHERE state_token_hash = ?
            """,
            (hash_state_token(state_token),),
        ).fetchone()
    return row_to_connection_request(row) if row is not None else None


def update_connection_request(
    request_id: str,
    *,
    status: str,
    zernio_account_id: str | None = None,
    selected_phone_number_id: str | None = None,
    display_phone_number: str | None = None,
    callback_payload: dict[str, Any] | None = None,
    error_summary: str | None = None,
) -> ConnectionRequest:
    if status not in CONNECTION_REQUEST_STATUSES:
        raise ValueError("Invalid connection request status.")
    init_db()
    now = utc_now()
    callback_payload_json = (
        json.dumps(callback_payload, sort_keys=True, ensure_ascii=False)
        if callback_payload is not None
        else None
    )
    with _connect() as conn:
        conn.execute(
            """
            UPDATE connection_requests
            SET status = ?,
                zernio_account_id = COALESCE(?, zernio_account_id),
                selected_phone_number_id = COALESCE(?, selected_phone_number_id),
                display_phone_number = COALESCE(?, display_phone_number),
                callback_payload_json = COALESCE(?, callback_payload_json),
                error_summary = ?,
                updated_at = ?
            WHERE id = ?
            """,
            (
                status,
                zernio_account_id,
                selected_phone_number_id,
                display_phone_number,
                callback_payload_json,
                error_summary,
                now,
                request_id,
            ),
        )
        row = conn.execute(
            "SELECT * FROM connection_requests WHERE id = ?",
            (request_id,),
        ).fetchone()
    if row is None:
        raise ValueError("Connection request not found.")
    return row_to_connection_request(row)


def upsert_tenant_channel_connection(
    *,
    tenant_id: str,
    channel: str = "whatsapp",
    provider: str = "zernio",
    status: str,
    zernio_profile_id: str | None = None,
    zernio_account_id: str | None = None,
    phone_number_id: str | None = None,
    display_phone_number: str | None = None,
    waba_id: str | None = None,
    metadata: dict[str, Any] | None = None,
    last_request_id: str | None = None,
    last_error: str | None = None,
    connected_at: str | None = None,
) -> TenantChannelConnection:
    if status not in TENANT_CONNECTION_STATUSES:
        raise ValueError("Invalid tenant channel connection status.")
    init_db()
    now = utc_now()
    metadata_json = json.dumps(metadata or {}, sort_keys=True, ensure_ascii=False)
    if status == "connected" and connected_at is None:
        connected_at = now
    with _connect() as conn:
        conn.execute(
            """
            INSERT INTO tenant_channel_connections (
                tenant_id,
                channel,
                provider,
                status,
                zernio_profile_id,
                zernio_account_id,
                phone_number_id,
                display_phone_number,
                waba_id,
                metadata_json,
                last_request_id,
                last_error,
                connected_at,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT (tenant_id, channel, provider)
            DO UPDATE SET status = excluded.status,
                          zernio_profile_id = excluded.zernio_profile_id,
                          zernio_account_id = excluded.zernio_account_id,
                          phone_number_id = excluded.phone_number_id,
                          display_phone_number = excluded.display_phone_number,
                          waba_id = excluded.waba_id,
                          metadata_json = excluded.metadata_json,
                          last_request_id = excluded.last_request_id,
                          last_error = excluded.last_error,
                          connected_at = excluded.connected_at,
                          updated_at = excluded.updated_at
            """,
            (
                tenant_id,
                channel,
                provider,
                status,
                zernio_profile_id,
                zernio_account_id,
                phone_number_id,
                display_phone_number,
                waba_id,
                metadata_json,
                last_request_id,
                last_error,
                connected_at,
                now,
                now,
            ),
        )
        row = conn.execute(
            """
            SELECT * FROM tenant_channel_connections
            WHERE tenant_id = ? AND channel = ? AND provider = ?
            """,
            (tenant_id, channel, provider),
        ).fetchone()
    return row_to_tenant_channel_connection(row)


def get_tenant_channel_connection(
    tenant_id: str,
    *,
    channel: str = "whatsapp",
    provider: str = "zernio",
) -> TenantChannelConnection | None:
    init_db()
    with _connect() as conn:
        row = conn.execute(
            """
            SELECT * FROM tenant_channel_connections
            WHERE tenant_id = ? AND channel = ? AND provider = ?
            """,
            (tenant_id, channel, provider),
        ).fetchone()
    return row_to_tenant_channel_connection(row) if row is not None else None


def set_tenant_zernio_profile_id(
    *,
    tenant_id: str,
    zernio_profile_id: str,
    name: str | None = None,
    status: str = "active",
) -> None:
    init_db()
    now = utc_now()
    with _connect() as conn:
        conn.execute(
            """
            INSERT INTO tenants (
                slug,
                name,
                status,
                zernio_profile_id,
                created_at,
                updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT (slug)
            DO UPDATE SET name = COALESCE(excluded.name, tenants.name),
                          status = excluded.status,
                          zernio_profile_id = excluded.zernio_profile_id,
                          updated_at = excluded.updated_at
            """,
            (tenant_id, name, status, zernio_profile_id, now, now),
        )


def get_tenant_zernio_profile_id(tenant_id: str) -> str | None:
    init_db()
    with _connect() as conn:
        row = conn.execute(
            "SELECT zernio_profile_id FROM tenants WHERE slug = ?",
            (tenant_id,),
        ).fetchone()
    if row is None:
        return None
    value = row["zernio_profile_id"]
    return str(value) if value else None


def hash_state_token(state_token: str) -> str:
    return hashlib.sha256(state_token.encode("utf-8")).hexdigest()


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def row_to_connection_request(row: sqlite3.Row) -> ConnectionRequest:
    return ConnectionRequest(
        id=str(row["id"]),
        tenant_id=str(row["tenant_id"]),
        channel=str(row["channel"]),
        provider=str(row["provider"]),
        status=str(row["status"]),
        state_token_hash=str(row["state_token_hash"]),
        state_token_created_at=str(row["state_token_created_at"]),
        state_token_expires_at=row["state_token_expires_at"],
        auth_url=row["auth_url"],
        zernio_profile_id=row["zernio_profile_id"],
        zernio_account_id=row["zernio_account_id"],
        selected_phone_number_id=row["selected_phone_number_id"],
        display_phone_number=row["display_phone_number"],
        callback_payload_json=row["callback_payload_json"],
        error_summary=row["error_summary"],
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
    )


def row_to_tenant_channel_connection(row: sqlite3.Row) -> TenantChannelConnection:
    return TenantChannelConnection(
        id=int(row["id"]),
        tenant_id=str(row["tenant_id"]),
        channel=str(row["channel"]),
        provider=str(row["provider"]),
        status=str(row["status"]),
        zernio_profile_id=row["zernio_profile_id"],
        zernio_account_id=row["zernio_account_id"],
        phone_number_id=row["phone_number_id"],
        display_phone_number=row["display_phone_number"],
        waba_id=row["waba_id"],
        metadata_json=str(row["metadata_json"]),
        last_request_id=row["last_request_id"],
        last_error=row["last_error"],
        connected_at=row["connected_at"],
        created_at=str(row["created_at"]),
        updated_at=str(row["updated_at"]),
    )
